basePath: /v1
definitions:
  model.Article:
    properties:
      background_pic:
        example: http://example.com/a.png
        type: string
      background_random:
        example: true
        type: boolean
      background_visible:
        example: true
        type: boolean
      category:
        example: default
        type: string
      content:
        example: 你好，世界！
        type: string
      content_hash:
        type: string
      title:
        example: 世界，你好！
        type: string
    type: object
  model.User:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  response.MsgResponse:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: api.amujun.com
info:
  contact:
    email: support@swagger.io
    name: aumujun@gmail.com
    url: http://www.swagger.io/support
  description: 博客后台程序REST API接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OPiece
  version: 0.0.1
paths:
  /article/get:
    get:
      consumes:
      - application/json
      description: 文章获取接口
      parameters:
      - description: JWT用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求页数
        in: query
        name: page_size
        type: string
      - description: 请求页码
        in: query
        name: page_size
        type: string
      summary: 文章获取接口
      tags:
      - 文章管理相关接口
  /article/post:
    post:
      consumes:
      - application/json
      description: 按照一定规则新建文章
      parameters:
      - description: JWT用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章标题
        in: formData
        name: title
        required: true
        type: string
      - description: 文章内容
        in: formData
        name: content
        required: true
        type: string
      - description: 文章hash值，为空则后端计算
        in: formData
        name: content_hash
        type: string
      - description: 是否显示背景图，默认false，为true时必须选择设置random和pic其中之一
        in: formData
        name: background_visible
        type: boolean
      - description: 当background_visible为true时
        in: formData
        name: background_random
        type: boolean
      - description: 当background_visible为true时
        in: formData
        name: background_pic
        type: string
      produces:
      - application/json
      summary: 新增文章接口
      tags:
      - 文章管理相关接口
  /article/remove:
    post:
      consumes:
      - application/json
      description: 文章删除接口 接收一个文章对象
      parameters:
      - description: JWT用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章对象
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      summary: 文章删除接口
      tags:
      - 文章管理相关接口
  /upload/pic:
    post:
      consumes:
      - multipart/form-data
      description: 图片上传接口 单纯只接收图片
      parameters:
      - description: JWT用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 图片hash 为空则后端进行计算
        in: formData
        name: file_hash
        type: string
      - description: 图片
        in: formData
        name: local_file
        required: true
        type: file
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.MsgResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: 图片上传接口
      tags:
      - 上传管理相关接口
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录，返回JWT
      parameters:
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: 用户登录接口
      tags:
      - 用户管理相关接口
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: 用户注册接口
      tags:
      - 用户管理相关接口
swagger: "2.0"
